### ISSUE TITLE
Crash when trying to download/install BetterCrewLink

### ISSUE THREAD

**Issue by lacksfish** [MatuxGG/ModManager#38]
When trying to install BetterCrewLink, the ModManager crashes.

Image of crash report window: https://i.imgur.com/VLESTmi.png

Full error message:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Program Files\ModManager5\https:\goodloss.fr\bcl'
 ---> System.Net.WebException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Program Files\ModManager5\https:\goodloss.fr\bcl'
 ---> System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Program Files\ModManager5\https:\goodloss.fr\bcl'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean useAsync)
   --- End of inner exception stack trace ---
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean useAsync)
   at System.Net.FileWebRequest.CreateResponse()
   --- End of inner exception stack trace ---
   at System.Net.FileWebRequest.CreateResponse()
   at System.Net.FileWebRequest.<>c.<BeginGetResponse>b__59_0(Object s)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskToApm.End[TResult](IAsyncResult asyncResult)
   at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.FileWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at ModManager5.Classes.ModWorker.installBetterCrewlink(Mod m) in D:\visualstudio\ModManager5\ModManager5\Classes\ModWorker.cs:line 348
   at ModManager5.Classes.ModWorker.installAnyMod(Mod m) in D:\visualstudio\ModManager5\ModManager5\Classes\ModWorker.cs:line 326
   at ModManager5.Classes.ModManagerUI.<>c__DisplayClass41_1.<refreshModForm>b__5(Object sender, EventArgs e) in D:\visualstudio\ModManager5\ModManager5\Classes\ModManagerUI.cs:line 734
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Private.CoreLib.dll
----------------------------------------
ModManager5
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.0.0
    CodeBase: file:///C:/Program%20Files/ModManager5/ModManager5.dll
----------------------------------------
System.Runtime
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 5.0.17.0
    Win32 Version: 5.0.1722.21504
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.17/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 5.0.17.0
    Win32 Version: 5.0.1722.21504
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.17/System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 5.0.0.2
    Win32 Version: 5.0.1221.52207
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.17/System.Drawing.Common.dll
----------------------------------------
System.Threading
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Collections.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 5.0.1722.21504
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.17/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.17/System.Resources.Extensions.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/netstandard.dll
----------------------------------------
System.Memory
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Memory.dll
----------------------------------------
System.Drawing
    Assembly Version: 5.0.17.0
    Win32 Version: 5.0.1722.21504
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.17/System.Drawing.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.ObjectModel.dll
----------------------------------------
System.Linq
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Linq.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Runtime.Extensions.dll
----------------------------------------
System.Buffers
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Buffers.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.17/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.ComponentModel.dll
----------------------------------------
Octokit
    Assembly Version: 0.50.0.0
    Win32 Version: 0.50.0.0
    CodeBase: file:///C:/Program%20Files/ModManager5/Octokit.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/Microsoft.Win32.Registry.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.IO.FileSystem.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Diagnostics.Process.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///C:/Program%20Files/ModManager5/Newtonsoft.Json.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Collections.Concurrent.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Linq.Expressions.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Runtime.Numerics.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Private.Uri.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Data.Common.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Private.Xml.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Reflection.Emit.Lightweight.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Private.CoreLib.dll
----------------------------------------
Microsoft.VisualBasic.Forms
    Assembly Version: 5.0.17.0
    Win32 Version: 5.0.1722.21504
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.17/Microsoft.VisualBasic.Forms.dll
----------------------------------------
System.IO.FileSystem.DriveInfo
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.IO.FileSystem.DriveInfo.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Net.WebClient.dll
----------------------------------------
System.Net.Requests
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Net.Requests.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Net.Primitives.dll
----------------------------------------
System.Net.WebHeaderCollection
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Net.WebHeaderCollection.dll
----------------------------------------
System.Net.Http
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Net.Http.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Diagnostics.Tracing.dll
----------------------------------------
System.Net.ServicePoint
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Net.ServicePoint.dll
----------------------------------------
System.Net.Security
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Net.Sockets.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Net.NameResolution.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Collections.NonGeneric.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Security.Claims.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Threading.Overlapped.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Threading.ThreadPool.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.IO.Compression.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Text.RegularExpressions.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.1722.21314
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.17/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************

```

I think the issue is because the link in the first few lines of the error log is missing a backslash in `https:/`

It should be `https://`

**Comment by MatuxGG** [comment]
This issue was already known in the roadmap: https://trello.com/b/udEzNJEQ/goodloss-co
An update may come this week-end to fix this issue.

Thanks for reporting it !

**Comment by MatuxGG** [comment]
Hi! This should be solved now. Please, close this issue when it's fine for you ;)
